let User,CustomErrorHandler;_58c‍.x([["default",()=>_58c‍.o]]);_58c‍.w("../../models",[["User",["User"],function(v){User=v}]]);_58c‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req, res, next) {
    try {
      const user = await User.findOne({_id: req.user._id}).select(
        "-password -updatedAt -__v "
      );
      if (!user) {
        return next(CustomErrorHandler.notFound());
      }
      res.json(user);
    } catch (error) {
      return next(error);
    }
    
  },
};

_58c‍.d(userController);
